services:
  db:
    platform: linux/x86_64
    image: postgis/postgis:15-3.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --host=postgres_db -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 3
