

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 3s
      interval: 3s
      timeout: 2s
      retries: 10
    